#  conda env create -f environment.yml
#  conda env update --file environment.yml  --prune
name: imdb_env
channels:
  - conda-forge
dependencies:
  - python=3.5
  - pip
  - pip:
    - -r requirements.txt